# Generated by Django 5.2.8 on 2025-11-19 03:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrador', 'Administrador'), ('profesor', 'Profesor'), ('monitor', 'Monitor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20)),
                ('primer_nombre', models.CharField(blank=True, max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(blank=True, max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('estrato', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOL', 'Soltero/a'), ('CAS', 'Casado/a'), ('DIV', 'Divorciado/a'), ('VIU', 'Viudo/a'), ('UL', 'Unión Libre')], max_length=3)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte')], max_length=3)),
                ('numero_identificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('lugar_expedicion_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('lugar_residencia', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('sede', models.CharField(blank=True, max_length=100)),
                ('jornada', models.CharField(blank=True, max_length=50)),
                ('programa', models.CharField(blank=True, max_length=100)),
                ('grupo', models.CharField(blank=True, max_length=20)),
                ('periodo', models.CharField(blank=True, max_length=20)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('codigo_matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nivel_formacion', models.CharField(blank=True, max_length=100)),
                ('eps', models.CharField(blank=True, max_length=100)),
                ('ars', models.CharField(blank=True, max_length=100)),
                ('aseguradora', models.CharField(blank=True, max_length=100)),
                ('grupo_sisben', models.CharField(blank=True, max_length=50)),
                ('discapacidad', models.BooleanField(default=False)),
                ('medio_transporte', models.CharField(blank=True, max_length=100)),
                ('multiculturalidad', models.BooleanField(default=False)),
                ('zona', models.CharField(blank=True, choices=[('U', 'Urbana'), ('R', 'Rural')], max_length=1)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('PEN', 'Pendiente')], default='PEN', max_length=3)),
                ('tipo_cancelacion', models.CharField(blank=True, max_length=50)),
                ('fecha_matricula', models.DateTimeField(default=django.utils.timezone.now)),
                ('formalizada', models.BooleanField(default=False)),
                ('condicion_matricula', models.CharField(blank=True, max_length=100)),
                ('nivel_academico', models.CharField(blank=True, max_length=100)),
                ('ultimo_ano', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('ultimo_nivel_aprobado', models.CharField(blank=True, max_length=100)),
                ('titulo_alcanzado', models.CharField(blank=True, max_length=100)),
                ('graduado', models.BooleanField(default=False)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('municipio_institucion', models.CharField(blank=True, max_length=100)),
                ('nit_institucion', models.CharField(blank=True, max_length=20)),
                ('telefono_institucion', models.CharField(blank=True, max_length=15)),
                ('direccion_institucion', models.TextField(blank=True)),
                ('email_institucion', models.EmailField(blank=True, max_length=254)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('pertenece_regimen_contributivo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estudiantes_extras', models.ManyToManyField(blank=True, to='api.estudianteextra')),
                ('estudiantes', models.ManyToManyField(related_name='estudiantes', to='api.userprofile')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
