# Generated by Django 5.2.8 on 2025-11-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_asistencia_curso_registroasistencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Curso'},
        ),
        migrations.AlterModelOptions(
            name='registroasistencia',
            options={'verbose_name': 'Asistencias', 'verbose_name_plural': 'Asistencias'},
        ),
    ]
