# Generated by Django 5.2.8 on 2025-11-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_curso_options_alter_registroasistencia_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
