# Generated by Django 5.2.8 on 2025-11-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_registroasistencia_estudiante_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroAsistencia',
            new_name='Asistencia',
        ),
    ]
