# Generated by Django 5.2.8 on 2025-11-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_registroasistencia_asistencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado')], default='P', max_length=1),
        ),
    ]
