# Generated by Django 5.2.8 on 2025-11-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_curso_options_asistencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1),
        ),
    ]
