# Generated by Django 5.2.8 on 2025-11-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_curso_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estudiantes_extras',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='object_id',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='api.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='curso_estudiantes', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_monitor', to='api.userprofile'),
        ),
        migrations.DeleteModel(
            name='EstudianteExtra',
        ),
    ]
