# Generated by Django 5.2.8 on 2026-01-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='modulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
