# Generated by Django 5.2.8 on 2026-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_curso_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='jornada',
            field=models.CharField(default='MAÑANA 7 - 9:30', max_length=50),
        ),
    ]
