# Generated by Django 5.2.8 on 2026-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='jornada',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
