# Generated by Django 5.2.8 on 2026-01-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_userprofile_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('P', 'Pendiente')], default='PEN', max_length=3),
        ),
    ]
