# Generated by Django 5.2.8 on 2026-01-26 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userprofile_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 15, 20, 37, 432672, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 1, 26, 15, 20, 37, 432672, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 15, 20, 37, 431660, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_matricula',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 15, 20, 37, 430615, tzinfo=datetime.timezone.utc)),
        ),
    ]
