# Generated by Django 5.2.8 on 2026-01-27 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_asistencia_creado_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 12, 48, 50, 853678, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 1, 27, 12, 48, 50, 853678, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 12, 48, 50, 852679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_matricula',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 12, 48, 50, 851679, tzinfo=datetime.timezone.utc)),
        ),
    ]
