# Generated by Django 5.2.8 on 2026-01-27 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_asistencia_creado_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_matricula',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
