# Generated by Django 5.2.8 on 2026-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_asistencia_creado_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte'), ('EX', 'Estudiante Extra'), ('MN', 'Monitor')], max_length=3),
        ),
    ]
