# Generated by Django 5.2.8 on 2026-01-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_userprofile_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='PEN', max_length=3),
        ),
    ]
