# Generated by Django 5.2.8 on 2026-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_userprofile_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_institucion',
            new_name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='direccion_institucion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_graduacion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='graduado',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='municipio_institucion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nit_institucion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nivel_academico',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefono_institucion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='titulo_alcanzado',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ultimo_ano',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ultimo_nivel_aprobado',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('G', 'Graduado'), ('C', 'Cancelado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='formalizada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='multiculturalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pertenece_regimen_contributivo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
