# Generated by Django 5.2.8 on 2026-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_email_institucion_userprofile_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ultima_actualizacion2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
