# Generated by Django 5.2.8 on 2026-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userprofile_ultima_actualizacion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ultima_actualizacion2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='formalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pertenece_regimen_contributivo',
            field=models.BooleanField(default=False),
        ),
    ]
