# Generated by Django 5.2.8 on 2026-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_userprofile_ultima_actualizacion2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='formalizada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pertenece_regimen_contributivo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
