# Generated by Django 5.2.8 on 2026-02-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_curso_estudiantes_alter_curso_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='curso_estudiantes', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_monitor', to='api.userprofile'),
        ),
    ]
