# Generated by Django 5.2.8 on 2026-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_curso_estudiantes_alter_curso_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='creado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
