# Generated by Django 5.2.8 on 2026-02-23 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_asistencia_creado_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
