EXPECTED_HEADERS = [
    "Código de matrícula",
    "Primer nombre",
    "Segundo nombre",
    "Primer apellido",
    "Segundo apellido",
    "Tipo de identificación",
    "Número de identificación",
    "Lugar de expedición del documento",
    "Fecha de nacimiento",
    "Lugar de nacimiento",
    "Teléfono",
    "Celular",
    "Correo electrónico",
    "Dirección",
    "País",
    "Lugar de residencia",
    "Barrio",
    "Sexo",
    "Estrato",
    "Tipo de sangre",
    "EPS",
    "ARS",
    "Grupo Sisbén",
    "Zona",
    "Estado",
    "Tipo de cancelación",
    "Fecha de matrícula",
    "Sede",
    "Formalizada",
    "Jornada",
    "Grupo",
    "Período",
    "Nivel",
    "Usuario",
    "Última fecha de actualización",
    "Edad",
    "Pertenece al régimen contributivo",
    "Estado civil",
    "Aseguradora",
    "Nivel de formación",
    "Ocupación",
    "Discapacidad",
    "Medio de transporte",
    "Multiculturalidad",
    "Programa",
    "Cond. Matrícula",
]
